name: Auto Assign Reviewer

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR
        uses: auto-assign-action@v1
        with:
          reviewers: zelebwr, AtokTajuddin

          numberOfReviewers: 1