name: Auto Assign Reviewer

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR
        uses: kentaro-m/auto-assign-action@v1.2.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"